[package]
name = "spectral"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
egui_double_slider = "1.0.0"
egui_extras = "0.33.3"
eyre = "0.6.12"
rand = "0.9.2"
rfd = "0.17.2"
rodio = "0.20.1"
rustfft = "6.4.1"
